/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Video = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'file' : ExternalBlob,
  'description' : IDL.Text,
  'uploadTimestamp' : Time,
  'viewCount' : IDL.Nat,
});
export const UploadResult = IDL.Variant({
  'ok' : IDL.Text,
  'error' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'followUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'uploadThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
      ],
      [UploadResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Video = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'file' : ExternalBlob,
    'description' : IDL.Text,
    'uploadTimestamp' : Time,
    'viewCount' : IDL.Nat,
  });
  const UploadResult = IDL.Variant({ 'ok' : IDL.Text, 'error' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'followUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Text], [IDL.Opt(Video)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'uploadThumbnail' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
        ],
        [UploadResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };